version: '3'

services:
  db:
    image: postgres:9.6
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_PASSWORD: ${PASSWORD}

    container_name: "questionsdb"
    volumes: 
      - ./postgres:/var/lib/postgresql/data
  db2:
    image: postgres:9.6
    restart: always
    ports: 
      - "5431:5432"
    environment:
      POSTGRES_DB: "test"
      POSTGRES_PASSWORD: "password"

    container_name: "users"
    volumes: 
      - ./postgres:/var/lib/postgresql/data